{
  "hash": "0b47b62451b410733104bcc0171572d1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take Home Exercise 02\"\nauthor: \"Pan Mingwei\"\ndate: \"September 24, 2024\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  cache: true\n  freeze: true\nformat: \n  html: \n    code-fold: false\n    code-summary: \"Click to expand/collapse code\"\n---\n\n\n\n# 1. Overview\n\nDrug abuse is associated with significant negative health, financial and social consequences. Yet, illicit drug consumption remains highly prevalent and continues to be a growing problem worldwide. In 2021, 1 in 17 people aged 15–64 in the world had used a drug in the past 12 months. Notwithstanding population growth, the estimated number of drug users grew from 240 million in 2011 to 296 million in 2021.\n\nThe geopolitics of Thailand which is near the [Golden Triangle](https://en.wikipedia.org/wiki/Golden_Triangle_(Southeast_Asia)) of Indochina, the largest drug production site in Asia, and the constant transportation infrastructure development made Thailand became market and transit routes for drug trafficking to the third countries.\n\nIn Thailand, drug abuse is one of the major social issue. There are about 2.7 million youths using drugs in Thailand. Among youths aged between 15 and 19 years, there are about 300,000 who have needs for drug treatment. Most of Thai youths involved with drugs are vocational-school students, which nearly doubles in number compared to secondary-school students.\n\n## 1.1 The Objective\n\nThis take-home exercise will focus on determining:\n\n-   if the key indicators of drug abuse of Thailand are independent from space.\n\n-   If the indicators of drug abuse is indeed spatial dependent, then, identify where are the clusters and outliers, and the hotspots.\n\n-   Last, investigate how the observation above evolve over time.\n\n## 1.2 The Task\n\n-   Use **sf** and **tidyverse** to prepare the geospatial data layer:\n\n    -   a study area layer of province level(including Bangkok).\n\n    -   a drug abuse indicators layer within the study area.\n\n-   Perform Global Spatial Autocorrelation Analysis using **sfdep**.\n\n-   Perform Local Spatial Autocorrelation Analysis using **sfdep**.\n\n-   Analysis the spatial patterns.\n\n## 1.3 The Data\n\n-   [Thailand Drug Offenses \\[2017-2022\\]](https://www.kaggle.com/datasets/thaweewatboy/thailand-drug-offenses-2017-2022) at Kaggle.\n\n-   [Thailand - Subnational Administrative Boundaries](https://data.humdata.org/dataset/cod-ab-tha?) at HDX. You are required to use the province boundary data set.\n\n# 2. Getting Started\n\n## 2.1 Load R Packages\n\n-   **sf** is use for importing and handling geospatial data in R,\n\n-   **tidyverse** is mainly use for wrangling attribute data in R,\n\n-   **sfped,** builds on the great shoulders of spdep package for spatial dependence. sfdep creates an sf and tidyverse friendly interface\n\n-   **tmap** will be used to prepare cartographic quality choropleth map.\n\n-   **gridExtra**, will be used to arrange grid-based plot, such as ggplot.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, sfdep, tmap, tidyverse, gridExtra)\n```\n:::\n\n\n\n## 2.2 Load the Data\n\n### 2.2.1 Geospatial Data\n\nLoading the Thailand_Subnational_Administrative1_Boundaries dataset, which contain the province boundary including Bandkok of Thailand. Using `st_read()` of **sf** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_sf <- st_read(dsn = \"data/geospatial\", \n                 layer = \"Thailand_Subnational_Administrative1_Boundaries\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Thailand_Subnational_Administrative1_Boundaries' from data source `/Users/mingwei/Desktop/SMU/Y3S1/IS415/xXxPMWxXx/IS415-GAA/Take-home_Ex/Take-home_Ex02/data/geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 77 features and 16 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\nThere are 77 geographic features, which aligns with expectations. This includes 76 provinces at the first-order administrative level and the capital city, Bangkok.\n\nNext, lets visualise **thailand_sf** using **tmap** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(thailand_sf)+\n  tm_fill(col=\"white\")+\n  tm_borders(col = \"black\", lwd=0.5, alpha=0.5)+\n  tm_layout(\n    main.title = \"Thailand Provinces (including Bandkok)\",\n    main.title.size = 1.5,\n    main.title.position = \"center\",\n    legend.show = FALSE,\n     frame = FALSE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-3-1.png){width=1152}\n:::\n:::\n\n\n\n### 2.2.2 Aspatial Data\n\nLoad Thailand drug offenses\\[2017 - 2022\\] dataset, using **`read_csv()`** from **readr** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug <- read_csv(\"data/aspatial/thai_drug_offenses_2017_2022.csv\")\n```\n:::\n\n\n\n# 3. Data Wrangling\n\n## 3.1 Remove Columns\n\nAs there some columns that would not be useful in our analysis. Therefore, it is good practice by removing those column.\n\nBefore we removing the column. Lets list down the column for the two data set.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(thailand_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Shape_Leng\" \"Shape_Area\" \"ADM1_EN\"    \"ADM1_TH\"    \"ADM1_PCODE\"\n [6] \"ADM1_REF\"   \"ADM1ALT1EN\" \"ADM1ALT2EN\" \"ADM1ALT1TH\" \"ADM1ALT2TH\"\n[11] \"ADM0_EN\"    \"ADM0_TH\"    \"ADM0_PCODE\" \"date\"       \"validOn\"   \n[16] \"validTo\"    \"geometry\"  \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(drug)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"fiscal_year\"            \"types_of_drug_offenses\" \"no_cases\"              \n[4] \"province_th\"            \"province_en\"           \n```\n\n\n:::\n:::\n\n\n\nBased on the columns list on the two dataset and after browsing the data, the following fields I will keep:\n\n-   thailand_sf\n\n    -   ADM1_EN (common field with the drug dataset) =\\> column 3\n\n    -   geometry =\\> column 17\n\n-   drug\n\n    -   fiscal_year =\\> column 1\n\n    -   types_of_drug_offenses =\\> column 2\n\n    -   no_cases =\\> column 3\n\n    -   province_en =\\> column 5\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_sf <- thailand_sf %>%\n  select(\"province_en\" = 3,17) # change the ADM1_EN to province_en\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug <- drug %>%\n  select(1:3,5)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(apply(drug, 1, function(x) any(is.na(x))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n## 3.2 Checking the common field\n\nSince we need to join the two datasets, it’s important to ensure that all the values in the common column match correctly.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_match <- setdiff(thailand_sf$province_en, drug$province_en)\ncheck_match # print the mismatch field in thailand_sf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Lop Buri\"  \"Bueng Kan\"\n```\n\n\n:::\n\n```{.r .cell-code}\ncheck_match <- setdiff(drug$province_en, thailand_sf$province_en)\ncheck_match # print the mismatch field in drug\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Loburi\"  \"buogkan\"\n```\n\n\n:::\n:::\n\n\n\nI observe that two provinces have names in different formats (\"Lop Buri\" and \"Bueng Kan\"). Let's modify the values in the `drug` dataset to match the naming convention used in the `thailand_sf` dataset.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug <- drug %>%\n  mutate(province_en = case_when(\n    province_en == \"Loburi\" ~ \"Lop Buri\",\n    province_en == \"buogkan\" ~ \"Bueng Kan\",\n    TRUE ~ province_en\n  ))\n```\n:::\n\n\n\nLets check, if there still have any mismatch.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_match <- setdiff(thailand_sf$province_en, drug$province_en)\ncheck_match\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncharacter(0)\n```\n\n\n:::\n:::\n\n\n\n## 3.3 Checking Types of Drug Offenses\n\nAs in the dataset, there are many different types of drug offenses. In order to get better insight. I decide to further check in the column and see which are the type I should consider.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique_types <- unique(drug$types_of_drug_offenses)\nprint(unique_types)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"drug_use_cases\"                                        \n [2] \"suspects_in_drug_use_cases\"                            \n [3] \"possession_cases\"                                      \n [4] \"suspects_in_possession_cases\"                          \n [5] \"possession_with_intent_to_distribute_cases\"            \n [6] \"suspects_in_possession_with_intent_to_distribute_cases\"\n [7] \"trafficking_cases\"                                     \n [8] \"suspects_in_trafficking_cases\"                         \n [9] \"production_cases\"                                      \n[10] \"suspects_in_production_cases\"                          \n[11] \"import_cases\"                                          \n[12] \"suspects_in_import_cases\"                              \n[13] \"export_cases\"                                          \n[14] \"suspects_in_export_cases\"                              \n[15] \"conspiracy_cases\"                                      \n[16] \"suspects_in_conspiracy_cases\"                          \n```\n\n\n:::\n:::\n\n\n\nTo get a better sense of the field, and decide which type I should focus on. I will group the type using the code chunk.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_counts <- drug %>%\n  group_by(types_of_drug_offenses) %>%\n  summarise(total_cases = sum(no_cases, na.rm = TRUE),, .groups = 'drop')\n```\n:::\n\n\n\nTo visualise the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(drug_counts, aes(x = types_of_drug_offenses, y = total_cases, fill = types_of_drug_offenses)) +\n  geom_bar(stat = \"identity\") +  # Use stat = \"identity\" for summarized data\n  labs(title = \"Total Cases of Drug Offenses by Type\",\n       x = \"Types of Drug Offenses\",\n       y = \"Total Cases\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels for better visibility\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-15-1.png){width=1152}\n:::\n:::\n\n\n\nBased on the plot,in order to focuse on the drug abuse case, I will retain the drug use cases.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_use_cases <- drug %>%\n  filter(types_of_drug_offenses == \"drug_use_cases\")\n```\n:::\n\n\n\nSince, there is no mismatch in the province_en column, we can combine both data frame using **`left_join()`** of **dplyr** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_use_cases <- left_join(thailand_sf, drug_use_cases)\n```\n:::\n\n\n\nLets visualising the drug use case over the years.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(drug_use_cases) +\n  tm_fill(\"no_cases\", \n          style = \"quantile\", \n          palette = \"Blues\",\n          title = \"total_cases\") +\n  tm_layout(main.title = \"Distribution of drug use cases\",\n            main.title.position = \"center\",\n            main.title.size = 1.2,\n            legend.height = 0.45, \n            legend.width = 0.35,\n            frame = TRUE) +\n  tm_facets(by = \"fiscal_year\", free.coords = FALSE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", size = 2) +\n  tm_scale_bar() +\n  tm_grid(alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-18-1.png){width=1152}\n:::\n:::\n\n\n\n# 4. Global Measures of Spatial Autocorrelation\n\nTo evaluate the overall degree of spatial dependence (autocorrelation) across the entire study area for each year.\n\n## 4.1 Global Moran's I Test\n\nI decided to use Queen contiguity for the neighbors, as it shares both edges and corners, providing a more comprehensive result in helping me determine whether the drug use cases are independent of their locations.\n\nI've observed that Phuket(67) is an island, which means that `st_contiguity` cannot identify any polygon neighbors for it. Therefore, I will set allow_zero to be TRUE.\n\n![](website_img/Phuket_location.jpg){fig-align=\"center\"}\n\n::: panel-tabset\n## 2017\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Deriving Queen’s contiguity weights\nwm_q_2017 <- drug_use_cases %>%\n  filter(fiscal_year == 2017) %>%\n  mutate(nb = st_contiguity(geometry),\n         wt = st_weights(nb,\n                         style = \"W\", allow_zero = TRUE),\n         .before = 1)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglobal_moran_test(wm_q_2017$no_cases,\n                       wm_q_2017$nb,\n                       wm_q_2017$wt,\n                       zero.policy = TRUE,)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 1.5049, p-value = 0.06618\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.077263424      -0.013333333       0.003624223 \n```\n\n\n:::\n:::\n\n\n\nThe results show an I value of 0.077, is close to zero, and a p-value of 0.06618, which exceeds the alpha level of 0.05. Therefore, we **do not have sufficient statistical evidence** to reject the null hypothesis, indicating that the spatial distribution of drug use cases in Thailand was random in 2017.\n\nTo strengthen the finding, we can run Monte carlo simulation to perform the statistical test.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234) # To ensure reproducible\nmoran_mc_2017_res = global_moran_perm(wm_q_2017$no_cases,\n                       wm_q_2017$nb,\n                       wm_q_2017$wt,\n                        nsim=999,\n                       zero.policy = TRUE,)\nmoran_mc_2017_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.077263, observed rank = 922, p-value = 0.156\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\n\nFrom the simulation results, we can observed that the p-value have increased, which further indicate that we **cannot reject** the null hypothesis.\n\nLets check the summary statistics using **summary()** function.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary(moran_mc_2017_res$res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.14280 -0.05100 -0.02104 -0.01239  0.02079  0.20105 \n```\n\n\n:::\n:::\n\n\n\nTo visualise the monte-carlo simulation, we can plot a histogram. The statistic I value for 2017 was 0.07 which fall under the random section of the simulation result. As such, we **cannot reject** the null hypothesis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() + \n  aes(moran_mc_2017_res$res[1:999]) + \n  geom_histogram(colour=\"black\", fill=\"grey\") +\n  geom_vline(xintercept = 0, color = \"red\", linetype = \"solid\", size = 1) +\n  labs(title = \"Histogram of Simulated Moran's I For Thailand Drug Use Cases 2017\",\n       x = \"Simulated Moran's I\",\n       y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-23-1.png){width=1152}\n:::\n:::\n\n\n\n## 2018\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Deriving Queen’s contiguity weights\nwm_q_2018 <- drug_use_cases %>%\n  filter(fiscal_year == 2018) %>%\n  mutate(nb = st_contiguity(geometry),\n         wt = st_weights(nb,\n                         style = \"W\", allow_zero = TRUE),\n         .before = 1)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglobal_moran_test(wm_q_2018$no_cases,\n                       wm_q_2018$nb,\n                       wm_q_2018$wt,\n                       zero.policy = TRUE,)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 1.673, p-value = 0.04716\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.091283835      -0.013333333       0.003910294 \n```\n\n\n:::\n:::\n\n\n\nFrom the above result with I = 0.09 and the p-value = 0.4716 is smaller than alpha value of 0.05. Hence, we have statistical evidence to **reject** the null hypothesis and since the I value is positive but close to 0, so we can infer that the spatial distribution shows a **weak sign of clustering** in 2018.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234) # To ensure reproducible\nmoran_mc_2018_res = global_moran_perm(wm_q_2018$no_cases,\n                       wm_q_2018$nb,\n                       wm_q_2018$wt,\n                        nsim=999,\n                       zero.policy = TRUE,)\nmoran_mc_2018_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.091284, observed rank = 944, p-value = 0.112\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\n\nHowever, based on the simulation, we can observed that the p-value has become larger than the alpha value of 0.05. Hence, based on the simulation result, we **do not have statistical evidence** to **reject** the null hypothesis that the spatial distribution of drug use case in Thailand are resemble random distribution for Year 2018.\n\nTo check the summary statistics.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary(moran_mc_2018_res$res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.14516 -0.05257 -0.01834 -0.01137  0.02357  0.26485 \n```\n\n\n:::\n:::\n\n\n\nBased on the histogram, the result similar to Year 2017, the statistic I value still fall under the random section(0.09). As such, we **cannot reject** the null hypothesis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() + \n  aes(moran_mc_2018_res$res[1:999]) + \n  geom_histogram(colour=\"black\", fill=\"grey\") +\n  geom_vline(xintercept = 0, color = \"red\", linetype = \"solid\", size = 1) +\n  labs(title = \"Histogram of Simulated Moran's I For Thailand Drug Use Cases 2018\",\n       x = \"Simulated Moran's I\",\n       y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-28-1.png){width=1152}\n:::\n:::\n\n\n\n## 2019\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Deriving Queen’s contiguity weights\nwm_q_2019 <- drug_use_cases %>%\n  filter(fiscal_year == 2019) %>%\n  mutate(nb = st_contiguity(geometry),\n         wt = st_weights(nb,\n                         style = \"W\", allow_zero = TRUE),\n         .before = 1)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglobal_moran_test(wm_q_2019$no_cases,\n                       wm_q_2019$nb,\n                       wm_q_2019$wt,\n                       zero.policy = TRUE,)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 2.1385, p-value = 0.01624\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.138046280      -0.013333333       0.005010889 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234) # To ensure reproducible\nmoran_mc_2019_res = global_moran_perm(wm_q_2019$no_cases,\n                       wm_q_2019$nb,\n                       wm_q_2019$wt,\n                        nsim=999,\n                       zero.policy = TRUE,)\nmoran_mc_2019_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.13805, observed rank = 972, p-value = 0.056\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\n\nBased on the Moran I test and simulation result, we can observed that the p-value have become larger than 0.05 in the statistical test. Hence, we **do not have enough statistical evidence** to reject the null hypothesis that the spatial distribution of drug use case in Thailand are resemble random distribution for Year 2019. However, notice that the p-value is actually very close to the alpha value of 0.05, so based on this, we can infer that even we do not have enough statistical evidence to reject the null hypothesis, but it also give us insight that the drug use case in 2019, is probably higher than Year 2017 and 2018.\n\nCheck the summary statistics.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary(moran_mc_2019_res$res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.15737 -0.05923 -0.01686 -0.01095  0.02767  0.31845 \n```\n\n\n:::\n:::\n\n\n\nBased on the histogram, we can observed that the statistic I value of 0.13 fall under the random section but very close to the alpha-value section.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() + \n  aes(moran_mc_2019_res$res[1:999]) + \n  geom_histogram(colour=\"black\", fill=\"grey\") +\n  geom_vline(xintercept = 0, color = \"red\", linetype = \"solid\", size = 1) +\n  labs(title = \"Histogram of Simulated Moran's I For Thailand Drug Use Cases 2019\",\n       x = \"Simulated Moran's I\",\n       y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-33-1.png){width=1152}\n:::\n:::\n\n\n\n## 2020\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Deriving Queen’s contiguity weights\nwm_q_2020 <- drug_use_cases %>%\n  filter(fiscal_year == 2020) %>%\n  mutate(nb = st_contiguity(geometry),\n         wt = st_weights(nb,\n                         style = \"W\", allow_zero = TRUE),\n         .before = 1)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglobal_moran_test(wm_q_2020$no_cases,\n                       wm_q_2020$nb,\n                       wm_q_2020$wt,\n                       zero.policy = TRUE,)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 1.382, p-value = 0.08349\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.087091664      -0.013333333       0.005280586 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234) # To ensure reproducible\nmoran_mc_2020_res = global_moran_perm(wm_q_2020$no_cases,\n                       wm_q_2020$nb,\n                       wm_q_2020$wt,\n                        nsim=999,\n                       zero.policy = TRUE,)\nmoran_mc_2020_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.087092, observed rank = 924, p-value = 0.152\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\n\nBased on the Moran I test and simulation result, we can observed that the p-value have become larger than 0.05 in the statistical test. Hence, we **do not have enough statistical evidence** to reject the null hypothesis that the spatial distribution of drug use case in Thailand are resemble random distribution for Year 2020.\n\nThe summary of the simulation statistics.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary(moran_mc_2020_res$res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.15929 -0.06243 -0.02218 -0.01433  0.02699  0.33025 \n```\n\n\n:::\n:::\n\n\n\nBased on the histogram of the simulation, shows that the statistic I value of 0.08, fall in the random section.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() + \n  aes(moran_mc_2020_res$res[1:999]) + \n  geom_histogram(colour=\"black\", fill=\"grey\") +\n  geom_vline(xintercept = 0, color = \"red\", linetype = \"solid\", size = 1) +\n  labs(title = \"Histogram of Simulated Moran's I For Thailand Drug Use Cases 2020\",\n       x = \"Simulated Moran's I\",\n       y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-38-1.png){width=1152}\n:::\n:::\n\n\n\n## 2021\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Deriving Queen’s contiguity weights\nwm_q_2021 <- drug_use_cases %>%\n  filter(fiscal_year == 2021) %>%\n  mutate(nb = st_contiguity(geometry),\n         wt = st_weights(nb,\n                         style = \"W\", allow_zero = TRUE),\n         .before = 1)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglobal_moran_test(wm_q_2021$no_cases,\n                       wm_q_2021$nb,\n                       wm_q_2021$wt,\n                       zero.policy = TRUE,)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 2.862, p-value = 0.002105\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n       0.20376109       -0.01333333        0.00575372 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234) # To ensure reproducible\nmoran_mc_2021_res = global_moran_perm(wm_q_2021$no_cases,\n                       wm_q_2021$nb,\n                       wm_q_2021$wt,\n                        nsim=999,\n                       zero.policy = TRUE,)\nmoran_mc_2021_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.20376, observed rank = 993, p-value = 0.014\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\n\nBased on the Moran I test and simulation result, we can observed that the p-value is still smaller than 0.05 in the statistical test. Hence, we **have enough statistical evidence** to reject the null hypothesis that the spatial distribution of drug use case in Thailand are not resemble random distribution for Year 2021. Since I is positive value of 0.2, hence we can infer that the spatial distribution of drag use in Thailand in 2021 shows sign of **weak clustering**.\n\nTo check the simulation statisitcs.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary(moran_mc_2021_res$res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.23519 -0.06340 -0.01754 -0.01333  0.03027  0.29476 \n```\n\n\n:::\n:::\n\n\n\nBased on the histogram, our statistic I value of 0.20376 falls under the alpha-value range. Hence, we can reject the null hypothesis and can infer there is a weak sign of spatial autocorrelation in the drug use case across different locations.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() + \n  aes(moran_mc_2021_res$res[1:999]) + \n  geom_histogram(colour=\"black\", fill=\"grey\") +\n  geom_vline(xintercept = 0, color = \"red\", linetype = \"solid\", size = 1) +\n  labs(title = \"Histogram of Simulated Moran's I For Thailand Drug Use Cases 2021\",\n       x = \"Simulated Moran's I\",\n       y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-43-1.png){width=1152}\n:::\n:::\n\n\n\n## 2022\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Deriving Queen’s contiguity weights\nwm_q_2022 <- drug_use_cases %>%\n  filter(fiscal_year == 2022) %>%\n  mutate(nb = st_contiguity(geometry),\n         wt = st_weights(nb,\n                         style = \"W\", allow_zero = TRUE),\n         .before = 1)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglobal_moran_test(wm_q_2022$no_cases,\n                       wm_q_2022$nb,\n                       wm_q_2022$wt,\n                       zero.policy = TRUE,)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 2.7688, p-value = 0.002813\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.197931897      -0.013333333       0.005822019 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234) # To ensure reproducible\nmoran_mc_2022_res = global_moran_perm(wm_q_2022$no_cases,\n                       wm_q_2022$nb,\n                       wm_q_2022$wt,\n                        nsim=999,\n                       zero.policy = TRUE,)\nmoran_mc_2022_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.19793, observed rank = 994, p-value = 0.012\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\n\nSimilar to Year 2021, we can observed that the p-value is still smaller than 0.05 in the statistical test. Hence, we **have enough statistical evidence** to reject the null hypothesis that the spatial distribution of drug use case in Thailand are not resemble random distribution for Year 2022 and shows sign of **weak clustering**.\n\nLets check the summary statistics.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary(moran_mc_2022_res$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.21825 -0.05910 -0.01462 -0.01072  0.03411  0.30446 \n```\n\n\n:::\n:::\n\n\n\nTo visualise the monte-carlo simulation, we can plot a histogram. The statistic I value for 2022 was 0.19 which fall under the alpha-value of the simulation result. As such, we can infer there is a weak sign of spatial autocorrelation in the drug use case across different locations.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() + \n  aes(moran_mc_2022_res$res[1:999]) + \n  geom_histogram(colour=\"black\", fill=\"grey\") +\n  geom_vline(xintercept = 0, color = \"red\", linetype = \"solid\", size = 1) +\n  labs(title = \"Histogram of Simulated Moran's I For Thailand Drug Use Cases 2022\",\n       x = \"Simulated Moran's I\",\n       y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-48-1.png){width=1152}\n:::\n:::\n\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(wm_q_2017,\"data/rds/wm_q_2017.rds\")\nwrite_rds(wm_q_2018,\"data/rds/wm_q_2018.rds\")\nwrite_rds(wm_q_2019,\"data/rds/wm_q_2019.rds\")\nwrite_rds(wm_q_2020,\"data/rds/wm_q_2020.rds\")\nwrite_rds(wm_q_2021,\"data/rds/wm_q_2021.rds\")\nwrite_rds(wm_q_2022,\"data/rds/wm_q_2022.rds\")\n```\n:::\n\n\n\n## 4.2 Global Moran's I Test Overall Insight\n\n::: callout-tip\n## Overall Observation\n\n-   Overall, we can observed that from the **Year 2017 to 2019**, the trend are increasing in term of I value and decreasing in p-value. But the p-value over the three years are still larger than the alpha value of 0.05. Hence, we **do not have enough statistical evidence** to reject the null hypothesis that the spatial distribution of drug use case in Thailand are resemble random distribution.\n\n-   In the **Year** **2020**, the trend broke, with the I value decreasing instead of continuing to increase, and the p-value increasing instead of decreasing. This suggests a stronger indication of randomness in the distribution. I believe this change is due to COVID-19, which resulted in a decrease in recorded drug use cases.\n\n-   In the Year 2021 - 2022, there are enough statistical evidence to reject the null hypothesis and we can infer that the spatial distribution of drug use cases **shows sign of weak clustering.**\n\n-   Based on the histograms of the simulation results, we can observe that the distribution of the simulated Moran’s I values is predominantly skewed to the negative side, indicating that the data points exhibit a dispersed spatial pattern.\n:::\n\n## 4.3 Global Geary's C Test\n\nIn order to gain different insight into the spatial pattern of the drug use cases in Thailand. I will perform Global Geary's C as it focus more on local differences and more sensitive to local variability than Moran's I. Hence, it will be able to help to detect local variability and help in understand how strongly individual provinces deviate from the overall pattern in neighboring regions.\n\n::: panel-tabset\n## 2017\n\nTo performs Geary’s C test for spatial autocorrelation using [`global_c_test()`](https://sfdep.josiahparry.com/reference/global_c_test) from **sfdep** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglobal_c_test(wm_q_2017$no_cases,\n              wm_q_2017$nb,\n              wm_q_2017$wt,\n              randomization = TRUE,\n              allow_zero=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  x \nweights: listw  \nn reduced by no-neighbour observations \n\nGeary C statistic standard deviate = -0.18872, p-value = 0.5748\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n        1.0256614         1.0000000         0.0184905 \n```\n\n\n:::\n:::\n\n\n\nTo performs permutation test for Geary’s C statistic by using [`global_c_perm()`](https://sfdep.josiahparry.com/reference/global_c_perm) from **sfdep** packages.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\ngeary_mc_2017_res = global_c_perm(wm_q_2017$no_cases,\n              wm_q_2017$nb,\n              wm_q_2017$wt,\n              nsim = 999,\n              allow_zero = TRUE,)\ngeary_mc_2017_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 1.0257, observed rank = 629, p-value = 0.629\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n\nBased on the above actual and simulation statistic, with C = 1.0257, the drug use cases exhibits a slight tendency toward spatial dispersion, but the result is very close to 1, indicating near-randomness. The large simulated p-value(0.629) suggests that the spatial distribution is likely random, and there is **no significant evidence** of spatial autocorrelation in 2017.\n\nTo visvualising the Monte Carlo Geary's C.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary(geary_mc_2017_res$res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.3162  0.8991  0.9790  0.9845  1.0755  1.4784 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() + \n  aes(geary_mc_2017_res$res[1:999]) + \n  geom_histogram(colour=\"black\", fill=\"grey\") +\n  geom_vline(xintercept = 1, color = \"red\", linetype = \"solid\", size = 1) +\n  labs(title = \"Histogram of Simulated  Geary C Values For Thailand Drug Use Cases 2017\",\n       x = \"Simulated  Geary C\",\n       y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-53-1.png){width=1152}\n:::\n:::\n\n\n\n## 2018\n\nTo performs Geary’s C test for spatial autocorrelation using [`global_c_test()`](https://sfdep.josiahparry.com/reference/global_c_test) from **sfdep** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglobal_c_test(wm_q_2018$no_cases,\n              wm_q_2018$nb,\n              wm_q_2018$wt,\n              randomization = TRUE,\n              allow_zero=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  x \nweights: listw  \nn reduced by no-neighbour observations \n\nGeary C statistic standard deviate = -0.026269, p-value = 0.5105\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n       1.00342511        1.00000000        0.01700099 \n```\n\n\n:::\n:::\n\n\n\nTo performs permutation test for Geary’s C statistic by using [`global_c_perm()`](https://sfdep.josiahparry.com/reference/global_c_perm) from **sfdep** packages.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\ngeary_mc_2018_res = global_c_perm(wm_q_2018$no_cases,\n              wm_q_2018$nb,\n              wm_q_2018$wt,\n              nsim = 999,\n              allow_zero = TRUE,)\ngeary_mc_2018_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 1.0034, observed rank = 582, p-value = 0.582\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n\nBased on the above actual and simulation statistic, with C = 1.0034 and simulated p-value are very similar to Year 2017. Hence, we ca infer there is **no significant evidence** of spatial autocorrelation in 2018 as well.\n\nTo visvualising the Monte Carlo Geary's C.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary(geary_mc_2018_res$res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.3658  0.9025  0.9801  0.9838  1.0716  1.4479 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() + \n  aes(geary_mc_2018_res$res[1:999]) + \n  geom_histogram(colour=\"black\", fill=\"grey\") +\n  geom_vline(xintercept = 1, color = \"red\", linetype = \"solid\", size = 1) +\n  labs(title = \"Histogram of Simulated  Geary C Values For Thailand Drug Use Cases 2018\",\n       x = \"Simulated  Geary C\",\n       y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-57-1.png){width=1152}\n:::\n:::\n\n\n\n## 2019\n\nTo performs Geary’s C test for spatial autocorrelation using [`global_c_test()`](https://sfdep.josiahparry.com/reference/global_c_test) from **sfdep** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglobal_c_test(wm_q_2019$no_cases,\n              wm_q_2019$nb,\n              wm_q_2019$wt,\n              randomization = TRUE,\n              allow_zero=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  x \nweights: listw  \nn reduced by no-neighbour observations \n\nGeary C statistic standard deviate = 0.78768, p-value = 0.2154\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n       0.91637784        1.00000000        0.01127045 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\ngeary_mc_2019_res = global_c_perm(wm_q_2019$no_cases,\n              wm_q_2019$nb,\n              wm_q_2019$wt,\n              nsim = 999,\n              allow_zero = TRUE,)\ngeary_mc_2019_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.91638, observed rank = 244, p-value = 0.244\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n\nBased on the above actual and simulation statistic, with C = 0.91638, the drug use cases exhibits a slight tendency **toward spatial clustered,** but the result is close to 1, indicating near-randomness. The simulated p-value(0.224) which is larger than the alpha-value 0.05, suggests that the spatial distribution is likely random, and there is **not enough significant evidence** of spatial autocorrelation in 2019.\n\nTo visvualising the Monte Carlo Geary's C.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary(geary_mc_2019_res$res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.5495  0.9180  0.9862  0.9847  1.0591  1.3493 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() + \n  aes(geary_mc_2019_res$res[1:999]) + \n  geom_histogram(colour=\"black\", fill=\"grey\") +\n  geom_vline(xintercept = 1, color = \"red\", linetype = \"solid\", size = 1) +\n  labs(title = \"Histogram of Simulated  Geary C Values For Thailand Drug Use Cases 2019\",\n       x = \"Simulated  Geary C\",\n       y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-61-1.png){width=1152}\n:::\n:::\n\n\n\n## 2020\n\nTo performs Geary’s C test for spatial autocorrelation using [`global_c_test()`](https://sfdep.josiahparry.com/reference/global_c_test) from **sfdep** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglobal_c_test(wm_q_2020$no_cases,\n              wm_q_2020$nb,\n              wm_q_2020$wt,\n              randomization = TRUE,\n              allow_zero=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  x \nweights: listw  \nn reduced by no-neighbour observations \n\nGeary C statistic standard deviate = 0.47955, p-value = 0.3158\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n      0.952367243       1.000000000       0.009866203 \n```\n\n\n:::\n:::\n\n\n\nTo performs permutation test for Geary’s C statistic by using [`global_c_perm()`](https://sfdep.josiahparry.com/reference/global_c_perm) from **sfdep** packages.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\ngeary_mc_2020_res = global_c_perm(wm_q_2020$no_cases,\n              wm_q_2020$nb,\n              wm_q_2020$wt,\n              nsim = 999,\n              allow_zero = TRUE,)\ngeary_mc_2020_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.95237, observed rank = 324, p-value = 0.324\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n\nBased on the above actual and simulation statistic, with C = 0.95237 and the simulated p-value(0.324) similar to previous year (2020) suggests the drug use cases exhibits a slight tendency **toward spatial clustered** and the spatial distribution is likely random, and there is **not enough significant evidence** of spatial autocorrelation in 2020.\n\nTo visvualising the Monte Carlo Geary's C.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary(geary_mc_2020_res$res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.5720  0.9290  0.9944  0.9896  1.0558  1.3507 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() + \n  aes(geary_mc_2020_res$res[1:999]) + \n  geom_histogram(colour=\"black\", fill=\"grey\") +\n  geom_vline(xintercept = 1, color = \"red\", linetype = \"solid\", size = 1) +\n  labs(title = \"Histogram of Simulated  Geary C Values For Thailand Drug Use Cases 2020\",\n       x = \"Simulated  Geary C\",\n       y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-65-1.png){width=1152}\n:::\n:::\n\n\n\n## 2021\n\nTo performs Geary’s C test for spatial autocorrelation using [`global_c_test()`](https://sfdep.josiahparry.com/reference/global_c_test) from **sfdep** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglobal_c_test(wm_q_2021$no_cases,\n              wm_q_2021$nb,\n              wm_q_2021$wt,\n              randomization = TRUE,\n              allow_zero=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  x \nweights: listw  \nn reduced by no-neighbour observations \n\nGeary C statistic standard deviate = 1.8151, p-value = 0.03476\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n      0.843832653       1.000000000       0.007402704 \n```\n\n\n:::\n:::\n\n\n\nTo performs permutation test for Geary’s C statistic by using [`global_c_perm()`](https://sfdep.josiahparry.com/reference/global_c_perm) from **sfdep** packages.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\ngeary_mc_2021_res = global_c_perm(wm_q_2021$no_cases,\n              wm_q_2021$nb,\n              wm_q_2021$wt,\n              nsim = 999,\n              allow_zero = TRUE,)\ngeary_mc_2021_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.84383, observed rank = 61, p-value = 0.061\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n\nBased on the above actual and simulation statistic, with C = **0.84383** and actual p-value of **0.03476**, the drug use cases exhibits a slight tendency **toward spatial clustered** and we **can reject the null hypothesis** that the autocorrelation is unlikely to have occurred by random. However,the simulated p-value(**0.061**) which is larger than the alpha-value 0.05.\n\nThe difference between the actual p-value (0.034) and the simulated p-value (0.061) indicates that while the traditional test suggests **significant spatial clustering**, the Monte Carlo simulation shows **weaker evidence** for rejecting the null hypothesis of spatial randomness.\n\nTo visvualising the Monte Carlo Geary's C.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary(geary_mc_2021_res$res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.6844  0.9350  0.9918  0.9886  1.0443  1.2153 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() + \n  aes(geary_mc_2021_res$res[1:999]) + \n  geom_histogram(colour=\"black\", fill=\"grey\") +\n  geom_vline(xintercept = 1, color = \"red\", linetype = \"solid\", size = 1) +\n  labs(title = \"Histogram of Simulated  Geary C Values For Thailand Drug Use Cases 2021\",\n       x = \"Simulated  Geary C\",\n       y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-69-1.png){width=1152}\n:::\n:::\n\n\n\n## 2022\n\nTo performs Geary’s C test for spatial autocorrelation using [`global_c_test()`](https://sfdep.josiahparry.com/reference/global_c_test) from **sfdep** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglobal_c_test(wm_q_2022$no_cases,\n              wm_q_2022$nb,\n              wm_q_2022$wt,\n              randomization = TRUE,\n              allow_zero=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  x \nweights: listw  \nn reduced by no-neighbour observations \n\nGeary C statistic standard deviate = 1.9389, p-value = 0.02626\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n      0.837233817       1.000000000       0.007047089 \n```\n\n\n:::\n:::\n\n\n\nTo performs permutation test for Geary’s C statistic by using [`global_c_perm()`](https://sfdep.josiahparry.com/reference/global_c_perm) from **sfdep** packages.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\ngeary_mc_2022_res = global_c_perm(wm_q_2022$no_cases,\n              wm_q_2022$nb,\n              wm_q_2022$wt,\n              nsim = 999,\n              allow_zero = TRUE,)\ngeary_mc_2022_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.83723, observed rank = 46, p-value = 0.046\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n\nBased on the above actual and simulation statistic, unlike previous year(2021), with C = **0.83723** suggesting the drug use cases exhibits a slight tendency **toward spatial clustered.** With actual p-value of **0.2626** and simulated p-value of **0.046**, both is smaller than the alpha-value 0.05, hence, we **can reject the null hypothesis** that the autocorrelation is unlikely to have occurred by random and infer there is spatial autocorrelation of clustering in 2022.\n\nTo visvualising the Monte Carlo Geary's C.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary(geary_mc_2022_res$res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.6673  0.9333  0.9851  0.9845  1.0400  1.2253 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot() + \n  aes(geary_mc_2022_res$res[1:999]) + \n  geom_histogram(colour=\"black\", fill=\"grey\") +\n  geom_vline(xintercept = 1, color = \"red\", linetype = \"solid\", size = 1) +\n  labs(title = \"Histogram of Simulated  Geary C Values For Thailand Drug Use Cases 2022\",\n       x = \"Simulated  Geary C\",\n       y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-73-1.png){width=1152}\n:::\n:::\n\n\n:::\n\n## 4.4 Global Geary's Test Overall Insight\n\n::: callout-tip\n## Overall Observation\n\n-   Overall, the trend of what we have observed from Global Geary's test is similar to Global Moran's I Test. Except for Year 2021.\n\n-   **Year 2017 to 2019**, decreasing trend in C value and p-value.\n\n-   **Year 2020**, instead of continuing decreasing, both C value and p-value increased.\n\n-   However**, for Year 2021**, the C value and actual p-value suggest spatial clustered and we can reject the null hypothesis, but the simulated p-value become larger than alpha-value of 0.05, which shows weak evidence for us to reject the null hypothesis.\n\n-   **Year 2022**, There is sufficient statistical evidence for us to reject the null hypothesis and conclude that there is spatial autocorrelation indicating clustering.\n:::\n\n# 5. Local Measures of Spatial Autocorrelation\n\n## 5.1 Local Moran's I Test\n\nAs there are 3 p-value fields, for consistency, I will use **p_ii_sim** field, since I will simulate 1000 times and it will help in ensure robustness in my finding\n\n::: panel-tabset\n## 2017\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\nlisa_2017 <- wm_q_2017 %>% \n  mutate(local_moran = local_moran(\n    no_cases, nb, wt, nsim = 999,zero.policy = TRUE),\n         .before = 1) %>%\n  unnest(local_moran)\n```\n:::\n\n\n\nTo visualise local Moran's I and p-value.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(lisa_2017) +\n  tm_fill(\"ii\",\n          style = \"pretty\",\n          palette = \"BrBG\",\n          title = \"local moran statistics\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"local Moran's I of Drug Use Cases in 2017\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(lisa_2017) +\n  tm_fill(\"p_ii_sim\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of local Moran's I in 2017\",\n            main.title.size = 0.8)\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-75-1.png){width=1152}\n:::\n:::\n\n\n\nWe can observe that the area around Bangkok contains local outliers, as the number of cases in Bangkok is significantly higher than in the surrounding areas, which have relatively low case numbers. Additionally, there are three provinces on the northern side of Bangkok that exhibit local clustering.\n\n## 2018\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\nlisa_2018 <- wm_q_2018 %>% \n  mutate(local_moran = local_moran(\n    no_cases, nb, wt, nsim = 999,zero.policy = TRUE),\n         .before = 1) %>%\n  unnest(local_moran)\n```\n:::\n\n\n\nTo visualise local Moran's I and p-value.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(lisa_2018) +\n  tm_fill(\"ii\",\n          style = \"pretty\",\n          palette = \"BrBG\",\n          title = \"local moran statistics\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"local Moran's I of Drug Use Cases in 2018\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(lisa_2018) +\n  tm_fill(\"p_ii_sim\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of local Moran's I in 2018\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-77-1.png){width=1152}\n:::\n:::\n\n\n\nWe can see that the some provinces( Samut Prakan,Chachoengsao) near Bangkok have p_ii_sim values are below the alpha level of 0.05, with nearly being positive for the I value, except for Samut Sakhon(left side of Bangkok) and Nonthaburi(top side of Bangkok), which has a negative I value, indicating it being the outlier.\n\n## 2019\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\nlisa_2019 <- wm_q_2019 %>% \n  mutate(local_moran = local_moran(\n    no_cases, nb, wt, nsim = 999,zero.policy = TRUE),\n         .before = 1) %>%\n  unnest(local_moran)\n```\n:::\n\n\n\nTo visualise local Moran's I and p-value.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(lisa_2019) +\n  tm_fill(\"ii\",\n          style = \"pretty\",\n          palette = \"BrBG\",\n          title = \"local moran statistics\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"local Moran's I of Drug Use Cases in 2019\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(lisa_2019) +\n  tm_fill(\"p_ii_sim\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of local Moran's I in 2019\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-79-1.png){width=1152}\n:::\n:::\n\n\n\nWe can observed that the drug use cases in 2019 , is quite similar to previous year (2018), except that Samut Sakhon is no longer an outlier. And we have two province on top of the northern side.\n\n## 2020\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\nlisa_2020 <- wm_q_2020 %>% \n  mutate(local_moran = local_moran(\n    no_cases, nb, wt, nsim = 999,zero.policy = TRUE),\n         .before = 1) %>%\n  unnest(local_moran)\n```\n:::\n\n\n\nTo visualise local Moran's I and p-value.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(lisa_2020) +\n  tm_fill(\"ii\",\n          style = \"pretty\",\n          palette = \"BrBG\",\n          title = \"local moran statistics\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"local Moran's I of Drug Use Cases in 2020\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(lisa_2020) +\n  tm_fill(\"p_ii_sim\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of local Moran's I in 2020\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-81-1.png){width=1152}\n:::\n:::\n\n\n\nFrom the map, we can observe that there are not many significant changes compared to previous years, except for one province in the central become a weak cluster(I value = 0 to 1).\n\n## 2021\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\nlisa_2021 <- wm_q_2021 %>% \n  mutate(local_moran = local_moran(\n    no_cases, nb, wt, nsim = 999,zero.policy = TRUE),\n         .before = 1) %>%\n  unnest(local_moran)\n```\n:::\n\n\n\nTo visualise local Moran's I and p-value.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(lisa_2021) +\n  tm_fill(\"ii\",\n          style = \"pretty\",\n          palette = \"BrBG\",\n          title = \"local moran statistics\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"local Moran's I of Drug Use Cases in 2021\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(lisa_2021) +\n  tm_fill(\"p_ii_sim\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of local Moran's I in 2021\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-83-1.png){width=1152}\n:::\n:::\n\n\n\nBased on the above plots,we can see a cluster at the western region.\n\n## 2022\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\nlisa_2022 <- wm_q_2022 %>% \n  mutate(local_moran = local_moran(\n    no_cases, nb, wt, nsim = 999,zero.policy = TRUE),\n         .before = 1) %>%\n  unnest(local_moran)\n```\n:::\n\n\n\nTo visualise local Moran's I and p-value.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(lisa_2022) +\n  tm_fill(\"ii\",\n          style = \"pretty\",\n          palette = \"BrBG\",\n          title = \"local moran statistics\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"local Moran's I of Drug Use Cases in 2022\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(lisa_2022) +\n  tm_fill(\"p_ii_sim\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of local Moran's I in 2022\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-85-1.png){width=1152}\n:::\n:::\n\n\n\nThe plots for 2022 reveal distinct clustering areas in both the Northeast and Central regions, characterized by predominantly positive I values and p-values below the alpha threshold of 0.05. Additionally, there are two notable outliers: one located in the southern region and another in the northeastern region adjacent to the cluster.\n:::\n\n::: callout-tip\n## Overall Insight\n\n-   From **2017 to 2020,** the p-values below 0.05 are primarily concentrated near the Bangkok area and central region, indicating that outliers (with negative I values) and clusters (with positive I values) are likely located in this region.\n\n-   In **2021** and **2022**, there are clear sign of clustering and in 2022, there are two outliers as well.\n:::\n\n## 5.2 Local Indicators of Spatial Association(LISA)\n\nWe can utilize the LISA Cluster Map to highlight statistically significant areas, making it easier to identify spatial autocorrelation patterns in the data.\n\nAfter examining the skewness of the LISA for each year, the distribution of skewness appears to be **negatively skewed** (left side has more values than the positive side). Therefore, I will use the **median** for the LISA map analysis and filter by **p_ii_sim** value.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(gridExtra)\n\nplot_2017 <- ggplot(lisa_2017, aes(x = skewness)) + \n  geom_histogram(colour = \"black\", fill = \"grey\", bins = 30) +\n  labs(x = \"Skewness\", y = \"Frequency\", title = \"Skewness in 2017\") +\n  theme_minimal()\n\nplot_2018 <- ggplot(lisa_2018, aes(x = skewness)) + \n  geom_histogram(colour = \"black\", fill = \"grey\", bins = 30) +\n  labs(x = \"Skewness\", y = \"Frequency\", title = \"Skewness in 2018\") +\n  theme_minimal()\n\nplot_2019 <- ggplot(lisa_2019, aes(x = skewness)) + \n  geom_histogram(colour = \"black\", fill = \"grey\", bins = 30) +\n  labs(x = \"Skewness\", y = \"Frequency\", title = \"Skewness in 2019\") +\n  theme_minimal()\n\nplot_2020 <- ggplot(lisa_2020, aes(x = skewness)) + \n  geom_histogram(colour = \"black\", fill = \"grey\", bins = 30) +\n  labs(x = \"Skewness\", y = \"Frequency\", title = \"Skewness in 2020\") +\n  theme_minimal()\n\nplot_2021 <- ggplot(lisa_2021, aes(x = skewness)) + \n  geom_histogram(colour = \"black\", fill = \"grey\", bins = 30) +\n  labs(x = \"Skewness\", y = \"Frequency\", title = \"Skewness in 2021\") +\n  theme_minimal()\n\nplot_2022 <- ggplot(lisa_2022, aes(x = skewness)) + \n  geom_histogram(colour = \"black\", fill = \"grey\", bins = 30) +\n  labs(x = \"Skewness\", y = \"Frequency\", title = \"Skewness in 2022\") +\n  theme_minimal()\n\n# Arrange all six plots in a 2-column, 3-row layout\ngrid.arrange(plot_2017, plot_2018, plot_2019, plot_2020, plot_2021, plot_2022, ncol = 2, nrow = 3)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-86-1.png){width=1152}\n:::\n:::\n\n\n\nLocal Indicators of Spatial Association(LISA) interpretation:\n\n-   Clusters\n\n    -   **High-High**: High value area, surrounded by high value neighbours.\n\n    -   **Low-Low**: Low value area, surrounded by low value neightbours.\n\n-   Outliers\n\n    -   **High-Low**: High value area, surrounded by low value neighbours.\n\n    -   **Low-High**: Low value area, surrounded by high value neighbours.\n\nBelow is the code chunk that visualizes the LISA map alongside the drug use case map. I found this side-by-side comparison particularly useful for providing additional context, helping to better understand why specific locations are classified as clusters or outliers.\n\n::: panel-tabset\n## 2017\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlisa_sig_2017 <- lisa_2017  %>%\n  filter(p_ii_sim < 0.05)\nmap1 <- tm_shape(lisa_2017) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(lisa_sig_2017) +\n  tm_fill(\"median\") + \n  tm_borders(alpha = 0.4)\n\nmap2 <- tm_shape(lisa_2017) +\n  tm_polygons(\"no_cases\",\n          palette = \"Blues\",\n          style=\"quantile\", n=10)\n\ntmap_arrange(map1, map2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-87-1.png){width=1152}\n:::\n:::\n\n\n\n## 2018\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlisa_sig_2018 <- lisa_2018  %>%\n  filter(p_ii_sim < 0.05)\n\nmap1 <- tm_shape(lisa_2018) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(lisa_sig_2018) +\n  tm_fill(\"median\") + \n  tm_borders(alpha = 0.4)\n\nmap2 <- tm_shape(lisa_2018) +\n  tm_polygons(\"no_cases\",\n          palette = \"Blues\",\n          style=\"quantile\", n=10)\n\ntmap_arrange(map1, map2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-88-1.png){width=1152}\n:::\n:::\n\n\n\n## 2019\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlisa_sig_2019 <- lisa_2019  %>%\n  filter(p_ii_sim < 0.05)\n\nmap1 <- tm_shape(lisa_2019) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(lisa_sig_2019) +\n  tm_fill(\"median\") + \n  tm_borders(alpha = 0.4)\n\nmap2 <- tm_shape(lisa_2019) +\n  tm_polygons(\"no_cases\",\n          palette = \"Blues\",\n          style=\"quantile\", n=10)\n\ntmap_arrange(map1, map2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-89-1.png){width=1152}\n:::\n:::\n\n\n\n## 2020\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlisa_sig_2020 <- lisa_2020  %>%\n  filter(p_ii_sim < 0.05)\n\nmap1 <- tm_shape(lisa_2020) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(lisa_sig_2020) +\n  tm_fill(\"median\") + \n  tm_borders(alpha = 0.4)\n\nmap2 <- tm_shape(lisa_2020) +\n  tm_polygons(\"no_cases\",\n          palette = \"Blues\",\n          style=\"quantile\", n=10)\n\ntmap_arrange(map1, map2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-90-1.png){width=1152}\n:::\n:::\n\n\n\n## 2021\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlisa_sig_2021 <- lisa_2021  %>%\n  filter(p_ii_sim < 0.05)\n\nmap1 <- tm_shape(lisa_2021) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(lisa_sig_2021) +\n  tm_fill(\"median\") + \n  tm_borders(alpha = 0.4)\n\nmap2 <- tm_shape(lisa_2021) +\n  tm_polygons(\"no_cases\",\n          palette = \"Blues\",\n          style=\"quantile\", n=10)\n\ntmap_arrange(map1, map2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-91-1.png){width=1152}\n:::\n:::\n\n\n\n## 2022\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlisa_sig_2022 <- lisa_2022  %>%\n  filter(p_ii_sim < 0.05)\n\nmap1 <- tm_shape(lisa_2022) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(lisa_sig_2022) +\n  tm_fill(\"median\") + \n  tm_borders(alpha = 0.4)\n\nmap2 <- tm_shape(lisa_2022) +\n  tm_polygons(\"no_cases\",\n          palette = \"Blues\",\n          style=\"quantile\", n=10)\n\ntmap_arrange(map1, map2, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-92-1.png){width=1152}\n:::\n:::\n\n\n:::\n\n::: callout-note\n## LISA Insight\n\n-   The LISA map provides a much clearer way to identify clusters, particularly distinguishing between high-value and low-value clusters. This approach simplifies the process compared to the Local Moran's I Test maps we plotted earlier, which required multiple maps and side-by-side comparisons to interpret the spatial patterns. With LISA, clusters are more visually intuitive, making it easier to draw insights from spatial autocorrelation.\n-   Note that since I am using the **median** instead of the **mean**, some provinces in the LISA map appear slightly different from the Local Moran's I test p-value map. I think the difference arises because the median is more robust to skewed data, which may influence the spatial patterns displayed.\n:::\n\n## 5.3 Hot Spot and Code Spot Area Analysis(HCSA) with local Gi\\*\n\nBeside LISA, we can use local Gi\\* statistic to detect hot spots (areas of high values surrounded by high values) and cold spots (areas of low values surrounded by low values). In this analysis, spatial clustering patterns are measured, and locations are classified as hot spots, cold spots, or neutral areas. I will be use local Gi\\*, which will consider itself.\n\n::: callout-warning\nThis analysis is not to identify outliers and need to use distance matrix with all positive value.\n:::\n\nIn the previous sections, I used queen contiguity to define neighbors. Since there are multiple methods for calculating neighbors, I will explore different approaches using the 2017 data to identify the most suitable one for our analysis using HCSA and to gain diverse insights. For the weights, I will continue utilizing `st_inverse_distance`.\n\n-   Queen Contiguity =\\> st_contiguity\n\n-   Neighbors from a distance =\\> st_dist_band\n\n-   K-Nearest Neighbors =\\> st_knn\n\nFirst, we need to derive a spatial weight matrix before computing the local Gi\\* statistics. As the local Gi\\* statistic requires a distance matrix, we use the distance matrix for this purpose.\n\nSince the geometry field in `drug_use_cases` contains multipolygons instead of polygons, I will apply `st_centroid` to extract the central points for each multipolygon. This ensures we can calculate the distances between these central points accurately for the analysis.\n\n::: panel-tabset\n## 2017 - Queen Contiguity\n\nBelow code chunk will compute spatial weight matrix.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nwm_idw_2017 <- drug_use_cases %>%\n  filter(fiscal_year == 2017) %>%\n  mutate(nb = include_self(st_contiguity(geometry)),\n         geometry_centroid = st_centroid(geometry), \n         wts = st_inverse_distance(nb, \n                              geometry_centroid, \n                              scale = 1,\n                              alpha = 1),\n         .before = 1)\n```\n:::\n\n\n\nTo compute the local G\\* and using **set.seed()** to ensure the computation is reproducible.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\nHCSA_2017 <- wm_idw_2017 %>% \n  mutate(local_Gi = local_gstar_perm(\n    no_cases, nb, wts, nsim = 999),\n         .before = 1) %>%\n  unnest(local_Gi)\n```\n:::\n\n\n\nVisualising Gi\\* and p_sim value using tmap at province level.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(HCSA_2017) +\n  tm_fill(\"gi_star\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"Gi* of Drug Use Cases in 2017\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(HCSA_2017) +\n  tm_fill(\"p_sim\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of Gi*\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-95-1.png){width=1152}\n:::\n:::\n\n\n\nVisualising the significant(p_sim \\< 0.05) HCSA map.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nHCSA_sig_2017 <- HCSA_2017  %>%\n  filter(p_sim < 0.05)\n\nmap1 <- tm_shape(HCSA_2017) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(HCSA_sig_2017) +\n  tm_fill(\"cluster\") + \n  tm_borders(alpha = 0.4)\n\nmap2 <- tm_shape(HCSA_2017) +\n  tm_polygons(\"no_cases\",\n          palette = \"Blues\",\n          style=\"quantile\", n=10)\n\ntmap_arrange(map1, map2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-96-1.png){width=1152}\n:::\n:::\n\n\n\n## 2017 - Neighbors from a distance\n\nBelow code chunk will compute spatial weight matrix.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nwm_idw_2017_db <- drug_use_cases %>%\n  filter(fiscal_year == 2017) %>%\n  mutate(nb = include_self(st_dist_band(geometry, lower=0)),\n         geometry_centroid = st_centroid(geometry), \n         wts = st_inverse_distance(nb, \n                              geometry_centroid, \n                              scale = 1,\n                              alpha = 1),\n         .before = 1)\n```\n:::\n\n\n\nTo compute the local G\\* and using **set.seed()** to ensure the computation is reproducible.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\nHCSA_2017_db <- wm_idw_2017_db %>% \n  mutate(local_Gi = local_gstar_perm(\n    no_cases, nb, wts, nsim = 999),\n         .before = 1) %>%\n  unnest(local_Gi)\n```\n:::\n\n\n\nVisualising Gi\\* and p_sim value using tmap at province level.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(HCSA_2017_db) +\n  tm_fill(\"gi_star\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"Gi* of Drug Use Cases in 2017\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(HCSA_2017_db) +\n  tm_fill(\"p_sim\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of Gi*\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-99-1.png){width=1152}\n:::\n:::\n\n\n\nVisualising the significant(p_sim \\< 0.05) HCSA map.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nHCSA_sig_2017_db <- HCSA_2017_db  %>%\n  filter(p_sim < 0.05)\n\nmap1 <- tm_shape(HCSA_2017_db) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(HCSA_sig_2017_db) +\n  tm_fill(\"cluster\") + \n  tm_borders(alpha = 0.4)\n\nmap2 <- tm_shape(HCSA_2017_db) +\n  tm_polygons(\"no_cases\",\n          palette = \"Blues\",\n          style=\"quantile\", n=10)\n\ntmap_arrange(map1, map2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-100-1.png){width=1152}\n:::\n:::\n\n\n\n## 2017 - K-Nearest Neighbors\n\nBelow code chunk will compute spatial weight matrix.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nwm_idw_2017_k <- drug_use_cases %>%\n  filter(fiscal_year == 2017) %>%\n  mutate(nb = include_self(st_knn(geometry, k = 8)),\n         geometry_centroid = st_centroid(geometry), \n         wts = st_inverse_distance(nb, \n                              geometry_centroid,\n                              scale = 1,\n                              alpha = 1),\n         .before = 1)\n```\n:::\n\n\n\nTo compute the local G\\* and using **set.seed()** to ensure the computation is reproducible.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\nHCSA_2017_k <- wm_idw_2017_k %>% \n  mutate(local_Gi = local_gstar_perm(\n    no_cases, nb, wts, nsim = 999),\n         .before = 1) %>%\n  unnest(local_Gi)\n```\n:::\n\n\n\nVisualising Gi\\* and p_sim value using tmap at province level.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(HCSA_2017_k) +\n  tm_fill(\"gi_star\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"Gi* of Drug Use Cases in 2017\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(HCSA_2017_k) +\n  tm_fill(\"p_sim\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of Gi*\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-103-1.png){width=1152}\n:::\n:::\n\n\n\nVisualising the significant(p_sim \\< 0.05) HCSA map.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nHCSA_sig_2017_k <- HCSA_2017_k  %>%\n  filter(p_sim < 0.05)\n\nmap1 <- tm_shape(HCSA_2017_k) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(HCSA_sig_2017_k) +\n  tm_fill(\"cluster\") + \n  tm_borders(alpha = 0.4)\n\nmap2 <- tm_shape(HCSA_2017_k) +\n  tm_polygons(\"no_cases\",\n          palette = \"Blues\",\n          style=\"quantile\", n=10)\n\ntmap_arrange(map1, map2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-104-1.png){width=1152}\n:::\n:::\n\n\n:::\n\n::: callout-tip\n-   Notice that for the HCSA map for Queen Contiguity, is actually every similar with what we have in LISA map, because of the same method on how we define neighbors.\n\n-   For distance-based neighbors, I am using the default upper threshold. From the plot, we can observe that some areas lose local context. For example, the three provinces at the right side of Bangkok all have relatively high `no_cases`, yet one of them is not identified as part of the high cluster.\n\n-   For K-Nearest Neighbors (KNN), the plot accurately represents the central region. However, a potential issue with KNN is that it disregards local context, as it doesn't account for whether neighboring provinces are adjacent. For instance, in the southern region, the provinces are arranged in a line, meaning that using KNN may select neighbors that are quite distant from the province itself. This can result in weaker or misleading spatial autocorrelation patterns.\n\n-   Hence, for the years 2018 to 2022, I will continue using Queen Contiguity to identify neighbors, as it considers all adjacent neighbors, providing a more precise representation of local spatial relationships.\n:::\n\n::: panel-tabset\n## 2018\n\nBelow code chunk will compute spatial weight matrix.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nwm_idw_2018 <- drug_use_cases %>%\n  filter(fiscal_year == 2018) %>%\n  mutate(nb = include_self(st_contiguity(geometry)),\n         geometry_centroid = st_centroid(geometry), \n         wts = st_inverse_distance(nb, \n                              geometry_centroid, \n                              scale = 1,\n                              alpha = 1),\n         .before = 1)\n```\n:::\n\n\n\nTo compute the local G\\* and using **set.seed()** to ensure the computation is reproducible.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\nHCSA_2018 <- wm_idw_2018 %>% \n  mutate(local_Gi = local_gstar_perm(\n    no_cases, nb, wts, nsim = 999),\n         .before = 1) %>%\n  unnest(local_Gi)\n```\n:::\n\n\n\nVisualising Gi\\* and p_sim value using tmap at province level.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(HCSA_2018) +\n  tm_fill(\"gi_star\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"Gi* of Drug Use Cases in 2018\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(HCSA_2018) +\n  tm_fill(\"p_sim\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of Gi*\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-107-1.png){width=1152}\n:::\n:::\n\n\n\nVisualising the significant(p_sim \\< 0.05) HCSA map.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nHCSA_sig_2018 <- HCSA_2018  %>%\n  filter(p_sim < 0.05)\n\nmap1 <- tm_shape(HCSA_2018) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(HCSA_sig_2018) +\n  tm_fill(\"cluster\") + \n  tm_borders(alpha = 0.4)\n\nmap2 <- tm_shape(HCSA_2018) +\n  tm_polygons(\"no_cases\",\n          palette = \"Blues\",\n          style=\"quantile\", n=10)\n\ntmap_arrange(map1, map2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-108-1.png){width=1152}\n:::\n:::\n\n\n\n## 2019\n\nBelow code chunk will compute spatial weight matrix.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nwm_idw_2019 <- drug_use_cases %>%\n  filter(fiscal_year == 2019) %>%\n  mutate(nb = include_self(st_contiguity(geometry)),\n         geometry_centroid = st_centroid(geometry), \n         wts = st_inverse_distance(nb, \n                              geometry_centroid, \n                              scale = 1,\n                              alpha = 1),\n         .before = 1)\n```\n:::\n\n\n\nTo compute the local G\\* and using **set.seed()** to ensure the computation is reproducible.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\nHCSA_2019 <- wm_idw_2019 %>% \n  mutate(local_Gi = local_gstar_perm(\n    no_cases, nb, wts, nsim = 999),\n         .before = 1) %>%\n  unnest(local_Gi)\n```\n:::\n\n\n\nVisualising Gi\\* and p_sim value using tmap at province level.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(HCSA_2019) +\n  tm_fill(\"gi_star\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"Gi* of Drug Use Cases in 2019\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(HCSA_2019) +\n  tm_fill(\"p_sim\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of Gi*\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-111-1.png){width=1152}\n:::\n:::\n\n\n\nVisualising the significant(p_sim \\< 0.05) HCSA map.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nHCSA_sig_2019 <- HCSA_2019  %>%\n  filter(p_sim < 0.05)\n\nmap1 <- tm_shape(HCSA_2019) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(HCSA_sig_2019) +\n  tm_fill(\"cluster\") + \n  tm_borders(alpha = 0.4)\n\nmap2 <- tm_shape(HCSA_2019) +\n  tm_polygons(\"no_cases\",\n          palette = \"Blues\",\n          style=\"quantile\", n=10)\n\ntmap_arrange(map1, map2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-112-1.png){width=1152}\n:::\n:::\n\n\n\n## 2020\n\nBelow code chunk will compute spatial weight matrix.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nwm_idw_2020 <- drug_use_cases %>%\n  filter(fiscal_year == 2020) %>%\n  mutate(nb = include_self(st_contiguity(geometry)),\n         geometry_centroid = st_centroid(geometry), \n         wts = st_inverse_distance(nb, \n                              geometry_centroid, \n                              scale = 1,\n                              alpha = 1),\n         .before = 1)\n```\n:::\n\n\n\nTo compute the local G\\* and using **set.seed()** to ensure the computation is reproducible.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\nHCSA_2020 <- wm_idw_2020 %>% \n  mutate(local_Gi = local_gstar_perm(\n    no_cases, nb, wts, nsim = 999),\n         .before = 1) %>%\n  unnest(local_Gi)\n```\n:::\n\n\n\nVisualising Gi\\* and p_sim value using tmap at province level.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(HCSA_2020) +\n  tm_fill(\"gi_star\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"Gi* of Drug Use Cases in 2020\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(HCSA_2020) +\n  tm_fill(\"p_sim\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of Gi*\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-115-1.png){width=1152}\n:::\n:::\n\n\n\nVisualising the significant(p_sim \\< 0.05) HCSA map.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nHCSA_sig_2020 <- HCSA_2020  %>%\n  filter(p_sim < 0.05)\n\nmap1 <- tm_shape(HCSA_2020) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(HCSA_sig_2020) +\n  tm_fill(\"cluster\") + \n  tm_borders(alpha = 0.4)\n\nmap2 <- tm_shape(HCSA_2020) +\n  tm_polygons(\"no_cases\",\n          palette = \"Blues\",\n          style=\"quantile\", n=10)\n\ntmap_arrange(map1, map2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-116-1.png){width=1152}\n:::\n:::\n\n\n\n## 2021\n\nBelow code chunk will compute spatial weight matrix.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nwm_idw_2021 <- drug_use_cases %>%\n  filter(fiscal_year == 2021) %>%\n  mutate(nb = include_self(st_contiguity(geometry)),\n         geometry_centroid = st_centroid(geometry), \n         wts = st_inverse_distance(nb, \n                              geometry_centroid, \n                              scale = 1,\n                              alpha = 1),\n         .before = 1)\n```\n:::\n\n\n\nTo compute the local G\\* and using **set.seed()** to ensure the computation is reproducible.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\nHCSA_2021 <- wm_idw_2021 %>% \n  mutate(local_Gi = local_gstar_perm(\n    no_cases, nb, wts, nsim = 999),\n         .before = 1) %>%\n  unnest(local_Gi)\n```\n:::\n\n\n\nVisualising Gi\\* and p_sim value using tmap at province level.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(HCSA_2021) +\n  tm_fill(\"gi_star\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"Gi* of Drug Use Cases in 2021\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(HCSA_2021) +\n  tm_fill(\"p_sim\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of Gi*\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-119-1.png){width=1152}\n:::\n:::\n\n\n\nVisualising the significant(p_sim \\< 0.05) HCSA map.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nHCSA_sig_2021 <- HCSA_2021  %>%\n  filter(p_sim < 0.05)\n\nmap1 <- tm_shape(HCSA_2021) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(HCSA_sig_2021) +\n  tm_fill(\"cluster\") + \n  tm_borders(alpha = 0.4)\n\nmap2 <- tm_shape(HCSA_2021) +\n  tm_polygons(\"no_cases\",\n          palette = \"Blues\",\n          style=\"quantile\", n=10)\n\ntmap_arrange(map1, map2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-120-1.png){width=1152}\n:::\n:::\n\n\n\n## 2022\n\nBelow code chunk will compute spatial weight matrix.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nwm_idw_2022 <- drug_use_cases %>%\n  filter(fiscal_year == 2022) %>%\n  mutate(nb = include_self(st_contiguity(geometry)),\n         geometry_centroid = st_centroid(geometry), \n         wts = st_inverse_distance(nb, \n                              geometry_centroid, \n                              scale = 1,\n                              alpha = 1),\n         .before = 1)\n```\n:::\n\n\n\nTo compute the local G\\* and using **set.seed()** to ensure the computation is reproducible.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\nHCSA_2022 <- wm_idw_2022 %>% \n  mutate(local_Gi = local_gstar_perm(\n    no_cases, nb, wts, nsim = 999),\n         .before = 1) %>%\n  unnest(local_Gi)\n```\n:::\n\n\n\nVisualising Gi\\* and p_sim value using tmap at province level.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(HCSA_2022) +\n  tm_fill(\"gi_star\") + \n  tm_borders(alpha = 0.5) +\n  tm_view(set.zoom.limits = c(6,8)) +\n  tm_layout(main.title = \"Gi* of Drug Use Cases in 2022\",\n            main.title.size = 0.8)\n\nmap2 <- tm_shape(HCSA_2022) +\n  tm_fill(\"p_sim\",\n          breaks = c(0, 0.001, 0.01, 0.05, 1),\n              labels = c(\"0.001\", \"0.01\", \"0.05\", \"Not sig\")) + \n  tm_borders(alpha = 0.5) +\n  tm_layout(main.title = \"p-value of Gi*\",\n            main.title.size = 0.8)\n\ntmap_arrange(map1, map2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-123-1.png){width=1152}\n:::\n:::\n\n\n\nVisualising the significant(p_sim \\< 0.05) HCSA map.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nHCSA_sig_2022 <- HCSA_2022  %>%\n  filter(p_sim < 0.05)\n\nmap1 <- tm_shape(HCSA_2022) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(HCSA_sig_2022) +\n  tm_fill(\"cluster\") + \n  tm_borders(alpha = 0.4)\n\nmap2 <- tm_shape(HCSA_2022) +\n  tm_polygons(\"no_cases\",\n          palette = \"Blues\",\n          style=\"quantile\", n=10)\n\ntmap_arrange(map1, map2,ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-124-1.png){width=1152}\n:::\n:::\n\n\n:::\n\n::: callout-tip\n## HCSA Insight\n\n-   In 2017, there were two cold spot areas—one located above Bangkok and another surrounding the city. Notably, the cold spot area above Bangkok coincided with the Low-Low cluster identified in the LISA map.\n\n-   By 2018, the cold spot above Bangkok had disappeared, while the area around Bangkok persisted. However, one province transitioned from a cold spot to a hot spot during this period.\n\n-   In 2019, only one province remained as a cold spot around Bangkok, down from three provinces in 2018, while a new cold spot emerged in a province to the north. Additionally, the number of hot spots surrounding Bangkok increased.\n\n-   In 2020, a new cold spot area appeared slightly above Bangkok, leaving only one province as a hot spot in the region.\n\n-   By 2021, the hot spots had vanished, and a large cold spot area emerged to the left of Bangkok.\n\n-   In 2022, the cold spot areas were reduced to two provinces, while a new hot spot emerged in the northern region.\n:::\n\n## 5.4 Emerging Hot Spot Analysis (EHSA)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}